version: '3.4'

services:
  temperature-api:
    container_name: temperature-api
    image: ${DOCKER_REGISTRY-}temperature-api
    depends_on:
      - redis-cache
      - authentication-api
    build:
      context: .
      dockerfile: TemperatureApi/Dockerfile
    ports:
      - 5002:443

  authentication-api:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authentication-api
    depends_on:
      - sql-server-db
    build:
      context: .
      dockerfile: AuthenticationApi/Dockerfile
    ports:
      - 5004:443

  sql-server-db:
    container_name: mssql-otel-sample_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "11433:1433"
    volumes:
      - mssql_otel_sample_db:/var/opt/mssql
    environment:
      SA_PASSWORD: "PasS1234"
      ACCEPT_EULA: "Y"

  redis-cache:
   container_name: redis-otel-sample-cache
   image: redis
   ports:
     - "6379:6379"  

volumes:
  mssql_otel_sample_db:

